product:
  per_page: 15
  limit: 4
  length: 100
cart:
  length: 50
bill_date: "%Y%m%d%H%M%S"
bill: "B"
open: 1
user:
  per_page: 10
image: img.jpg
category:
  per_page: 10
per_page: 10
max_recent: 4
date_format: "%Y-%m-%d"
weekday: 7
one: 1
eight: 8
product_img: ip.jpg
comment:
  per_page: 5
